steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    [ 'functions',
      'deploy',
      '$_FUNC_NAME',
      '--runtime',
      'python37',
      '--entry-point',
      'hello_world',
      '--source',
      'https://source.developers.google.com/projects/$PROJECT_ID/repos/$REPO_NAME/moveable-aliases/$BRANCH_NAME/paths//',
      '--trigger-http',
      '--allow-unauthenticated'
    ]
